"""empty message

Revision ID: 59678a010da9
Revises: ce5a06e79cbd
Create Date: 2025-10-22 13:35:13.838194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59678a010da9'
down_revision = 'ce5a06e79cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_from_id', sa.Integer(), nullable=True),
    sa.Column('user_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
